title: justinpenney.com
description: > # this means to ignore newlines until "baseurl:"
  This is the site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://justinpenney.com" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: '@jpenney'

# Author Settings
author: Justin Penney
author-img: justin-penney.jpg # add your photo
about-author: "Always dabbling. Currently obsessing on kayak fishing, ham radio, and bass playing. Professionally, an architect/developer working mostly in Python in Azure."
social-twitter: "@jpenney"
social-facebook: "justin.penney"
social-github: "jpenney78" # artemsheludko # add your Github handle
social-linkedin: "justinpenney" # add your Linkedin handle
social-email: "jpenney@gmail.com" # add your Email address

# Disqus
discus-identifier: #mr-brown # add your discus identifier

# Tracker
analytics: "G-J8JDSLS7YT" # Google Analytics

# Build Settingsgit push
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
