title: justinpenney.com
description: > # this means to ignore newlines until "baseurl:"
  This is the site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://justinpenney.com" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: '@jpenney'

# Author Settings
author: Justin Penney
author-img: justin-penney.jpg # add your photo
about-author: # About me
social-twitter: "@jpenney"
social-facebook: "justin.penney"
social-github: # artemsheludko # add your Github handle
social-linkedin: # add your Linkedin handle
social-email: # add your Email address

# Disqus
discus-identifier: #mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settingsgit push
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
